### PR TITLE
Duckdb

### LINKED ISSUE #47: Investigate DuckDB over SQLite for faster querying
https://duckdb.org/

### PR DESCRIPTION
**Pull request by ateucher**
WIP Closes #47.

With this, no longer required to manually build the sqlite database as the speedup of creating duckdb directly from the csv obviates the need.

### CODE REVIEW

**Comment by ateucher** [comment]
@j-krogh @KarHarker @joethorley @JessicaPenno @sebdalgarno 

I have completed (I think) a big update to the backend database for the historic data in rems, and would love if you can test it - through direct use and with shinyrems.

The update allows daily updates of the historic data (since the csv on DataBC is now being updated daily), and the creation of the database should be much quicker than before. I've switched from a sqlite backend to a new database called `duckdb`. So far my tests are looking good, but would love you to give it a test drive if you can.

I highly recommend running `rems:::burn_it_down()` before you start testing it (this will clear your existing data cache). You can test out the new rems using `install_github("bcgov/rems", ref = "duckdb")`, then run `download_historic_data()` as usual.

Please read the readme at: https://github.com/bcgov/rems/blob/duckdb/README.md for important (though minor) changes for interacting with the historic data - namely the need to run the new `connect_historic_db()` before `attach_historic_data()`, as well as the new timezone issues.

Thanks!
Andy

**Comment by sebdalgarno** [comment]
thanks @ateucher ! I will take a look at this over the next couple days.

**Comment by ateucher** [comment]
Two things to note:

1. The downloads from the BC Data Catalogue are a bit broken right now... you can try `download_historic_data()` but it is usually failng at 21%. The DataBC folks are working on a fix; I'll let you know once it's working to test again.
2. I've [opened a PR](https://github.com/cwida/duckdb/pull/1302) to add more timezone support to `duckdb` - if it's accepted it will make dealing with timezones in rems pretty much seamless.

**Comment by sebdalgarno** [comment]
@ateucher unfortunately `download_historic_data()` timed out on me. Let me know when it's working again.

**Comment by joethorley** [comment]
FWIW I currently get
```r
> rems::download_historic_data()
rems would like to store a copy of the historic ems data at /Users/joe/Library/Application Support/rems/duckdb/ems_historic.duckdb. Is that okay? 

1: Yes
2: No

Selection: 1
This is going to take a while...
Downloading latest 'historic' EMS data
  |=======================================================================| 100%

Error in handle_zip(ret) : object 'ret' not found
Backtrace:
    █
 1. └─rems::download_historic_data()
 2.   └─rems:::download_ems_data(url)
 3.     └─rems:::handle_zip(ret)
 4.       └─tools::file_ext(x)
 5.         └─base::regexpr("\\.([[:alnum:]]+)$", x)
> 
```

**Comment by ateucher** [comment]
Whoops, thanks @joethorley - should be fixed now

**Comment by JessicaPenno** [comment]
I was successful downloading data for a new project using the updated rems script. 

But I am getting the same error when trying to run the shinyapp for both historic and 2yr:

Listening on http://127.0.0.1:4154
Warning: Error in : 'use_butler' is not an exported object from 'namespace:waiter'
  77: stop
  76: getExportedValue
  75: ::
  72: shinyrems:::app_ui


I also got the below error when trying to run the 2yr dataset. This seemed to sort out now that I used rems  This will be an issue for those who only use R to access the ShinyApp and not the rems package itself. 

shinyrems::run_ems_app():
Downloading latest '2yr' EMS data from BC Data Catalogue (url: https://pub.data.gov.bc.ca/datasets/949f2233-9612-4b06-92a9-903e817da659/)
  |===========================================================| 100%

Error in if (ext == ".zip") { : missing value where TRUE/FALSE needed

**Comment by sebdalgarno** [comment]
@JessicaPenno I fixed the first error (use_butler not an exported...). Someone with privileges just needs to merge the pull request here: https://github.com/bcgov/shinyrems/pull/120 and then you can reinstall. 

I haven't looked into this in depth, but It seems like these changes to rems have broken some things - will require further updates/fixes.

**Comment by sebdalgarno** [comment]
see also issue https://github.com/bcgov/shinyrems/issues/119. It seems like it is unrelated to rems though...

**Comment by joethorley** [comment]
I can confirm the rems code now works for me
```r
> library(rems)
> download_historic_data()
rems would like to store a copy of the historic ems data at /Users/joe/Library/Application Support/rems/duckdb/ems_historic.duckdb. Is that okay? 

1: Yes
2: No

Selection: 1
This is going to take a while...
Downloading latest 'historic' EMS data
  |====================================================================================================================================| 100%

Unzipping...
Saving historic data at /Users/joe/Library/Application Support/rems/duckdb/ems_historic.duckdb
Adding database indexes
|============| 100%
Successfully downloaded and stored the historic EMS data.
You can access and subset it with the 'read_historic_data' function, or
          attach it as a remote data.frame with 'attach_historic_data()'
          which you can then query with dplyr
```

**Comment by JessicaPenno** [comment]
@sebdalgarno I just merged the pull request but am getting the same error.

@KarHarker can you test out ShinyREMS with the new updates and see if you get it working?

**Comment by ateucher** [comment]
I installed the newest shinyrems and rems (`install_github("bcgov/rems", ref = "duckdb")`) - and run the app - the app launches successfully (I tried 2yr and historic), but with zero rows of data...

**Comment by KarHarker** [comment]
@JessicaPenno I tested shinyrems after installing the duckdb changes (install_github("bcgov/rems", ref = "duckdb"))  and the historic option worked for me. I tested with a few different sites/parameters.

**Comment by ateucher** [comment]
Oh it does work for me too - I didn't realize I had to apply site and parameter filters first 🤦

**Comment by JessicaPenno** [comment]
I have it working now too!

**Comment by joethorley** [comment]
FWIW `connect_historic_db()` takes over 1 minute to run on my Mac.

``` r
library(rems)
time <- Sys.time()
rems::connect_historic_db()
#> Please remember to use 'disconnect_historic_db()' when you are finished querying the historic database.
#> <duckdb_connection 8f0b0 driver=<duckdb_driver 5aed0 dbdir='/Users/joe/Library/Application Support/rems/duckdb/ems_historic.duckdb' read_only=TRUE>>
Sys.time() - time
#> Time difference of 1.483121 mins
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sebdalgarno** [comment]
`download_historic_data` is timing out on me (3 times today) but I think this is likely due to unstable internet connection in masset, given everyone else is having luck.

**Comment by ateucher** [comment]
@joethorley yes it's slow for me too, however the creation of the database from the csv is orders of magnitude faster than with sqlite, so I hope the tradeoff is worth it, particularly since the historic data is now being updated daily. But I'm doing some profiling to see why it might be slow. It's been a while since I used rems - was `attach_historic_data()` pretty quick with the sqlite backend?

@sebdalgarno I'm afraid it might be your connection 😬

**Comment by joethorley** [comment]
@ateucher why does the database have to be created fresh every time the user tries to connect? shouldn't it be cached so that the user only has to pay this price at most once per day.

**Comment by ateucher** [comment]
The database isn't created each time the user connects... it is created only when the user runs `download_historic_data()`. But for some reason the connection to the database takes longer than expected.

**Comment by joethorley** [comment]
@ateucher - I don't remember how quick `attach_historic_data()` was

**Comment by ateucher** [comment]
I timed download -> connect -> attach -> query -> disconnect for the historic data, and though the download/load is quick, the rest is quite slow:

``` r
library(tictoc)
library(rems)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

start <- tic("download")
download_historic_data(TRUE, FALSE)
#> This is going to take a while...
#> Downloading latest 'historic' EMS data
#> Unzipping...
#> Saving historic data at /Users/ateucher/Library/Application Support/rems/duckdb/ems_historic.duckdb
#> Adding database indexes
#> Successfully downloaded and stored the historic EMS data.
#> You can access and subset it with the 'read_historic_data' function, or
#>         attach it as a remote data.frame with 'connect_historic_db()' and
#>         'attach_historic_data()' which you can then query with dplyr
toc()
#> download: 513.571 sec elapsed
tic("connect")
con <- connect_historic_db()
#> Please remember to use 'disconnect_historic_db()' when you are finished querying the historic database.
toc()
#> connect: 117.14 sec elapsed
tic("attach")
hist_tbl <- attach_historic_data(con)
toc()
#> attach: 0.711 sec elapsed
tic("dplyr")
hist_df <- hist_tbl %>%
  select(EMS_ID, PARAMETER, COLLECTION_START, RESULT) %>%
  filter(EMS_ID %in% c("0121580", "0126400"),
         PARAMETER %in% c("Aluminum Total", "Cadmium Total",
                          "Copper Total", " Zinc Total",
                          "Turbidity")) %>%
  collect()
toc()
#> dplyr: 2.925 sec elapsed
tic("disconnect")
disconnect_historic_db(con)
end <- toc()
#> disconnect: 1.572 sec elapsed

# Total time:
end$toc - start
#> elapsed 
#> 635.929
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm just doing a comparison with sqlite and will post here

**Comment by ateucher** [comment]
Here are the timings using the sqlite backend - way slower creation of the database, but really fast connect/attach/query:

``` r
library(tictoc)
library(rems)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

start <- tic("download")
download_historic_data(TRUE, FALSE)
#> This is going to take a while...
#> Downloading latest 'historic' EMS data
#> Unzipping...
#> Saving historic data at /Users/ateucher/Library/Application Support/rems/ems_historic.sqlite
#> Creating indexes
#> Successfully downloaded and stored the historic EMS data.
#> You can access and subset it with the 'read_historic_data' function, or
#>         attach it as a remote data.frame with 'connect_historic_db()' and
#>         'attach_historic_data()' which you can then query with dplyr
toc()
#> download: 1144.59 sec elapsed
tic("connect")
con <- connect_historic_db()
#> Please remember to use 'disconnect_historic_db()' when you are finished querying the historic database.
toc()
#> connect: 0.112 sec elapsed
tic("attach")
hist_tbl <- attach_historic_data(con)
toc()
#> attach: 0.67 sec elapsed
tic("dplyr")
hist_df <- hist_tbl %>%
  select(EMS_ID, PARAMETER, COLLECTION_START, RESULT) %>%
  filter(EMS_ID %in% c("0121580", "0126400"),
         PARAMETER %in% c("Aluminum Total", "Cadmium Total",
                          "Copper Total", " Zinc Total",
                          "Turbidity")) %>%
  collect()
toc()
#> dplyr: 0.666 sec elapsed
tic("disconnect")
disconnect_historic_db(con)
end <- toc()
#> disconnect: 0.002 sec elapsed

# Total time:
end$toc - start
#>  elapsed 
#> 1146.055
```

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ateucher** [comment]
I'm putting the `duckdb` update on hold for now... seems performance-wise it's not quite ready for primetime.

**Comment by ateucher** [comment]
Recent changes in duckdb are promising - ran the timings again with the unreleased v 0.2.5 and it looks like they've fixed much of the performance: https://github.com/bcgov/rems/blob/duckdb/scratch/time_duckdb_full_workflow.md.

However given we just released 0.6 with sqlite, will wait to implement this...

**Pull request merged**
