### PR TITLE
Sqlite direct download

### PR DESCRIPTION
**Pull request by ateucher**
This PR does two major things:

1. Provides the historic sqlite database as a direct download from a rems release. This means that `download_historic_data()` does not involve reading the csv from the BCDC and iteratively loading it into sqlite. That process is now done by the package maintainer and `download_historic_data()` simply downloads the sqlite file and stores it in the rems data dir.

2. Allow a user to specify/customize the location of the `sqlite` database via an option `rems.historic.path` - (`getOption("rems.historic.path", default = rems_data_dir())`)

### CODE REVIEW

**Comment by ateucher** [comment]
To test:
```r
remotes::install_github("bcgov/rems@sqlite-path")
rems:::burn_it_down()

### Restart R session before proceeding ###

library(rems)
download_historic_data()
read_historic_data(emsid = "0400203", from_date = as.Date("1984-11-20"),
                   to_date = as.Date("1991-05-11"))
```

**Comment by ateucher** [comment]
@HeatherGranger @sebdalgarno

**Comment by sebdalgarno** [comment]
this is a great idea @ateucher ! I have followed the instructions above. I am able to initiate downloading the data but have now failed on 5 attempts (all at different stages of completion). I do feel that my poor Haida Gwaii may be the culprit. Hopefully someone else can test as well to confirm.

**Review by HeatherGranger — COMMENTED** [review]
Ditto, great idea. I got a couple function errors when I ran it. Am I missing something?

` > download_historic_data()
Error in ._remsCache_$exists("cache_dates") : 
  attempt to apply non-function
> read_historic_data(emsid = "0400203", from_date = as.Date("1984-11-20"),
                    to_date = as.Date("1991-05-11"))
Error in ._remsCache_$exists("cache_dates") : 
  attempt to apply non-function`

**Comment by sebdalgarno** [comment]
@HeatherGranger can you try restarting your R session prior to running `library(rems)` and all that follows?

**Comment by ateucher** [comment]
Ah yes, I forgot to mention that. Instructions updated

**Comment by HeatherGranger** [comment]
That worked. It's currently downloading. I'll report back on it's success!

**Comment by HeatherGranger** [comment]
Success! downloaded, stored and read in the data.

**Comment by ateucher** [comment]
Thanks for testing @HeatherGranger - that's great!

**Comment by ateucher** [comment]
@sebdalgarno I've just pushed a commit to allow passing `httr::GET` configurations. Can you try with a really long timeout threshold (`timeout()` value is in seconds)? eg. 

```r
download_historic_data(ask = FALSE, force = TRUE, httr_config = timeout(5000))
```

**Comment by sebdalgarno** [comment]
@ateucher I'm trying now with `timeout(5000)` as suggested. Will report back soon!

**Comment by boshek** [comment]
Similar success over here 🎉

**Comment by ateucher** [comment]
Thanks @boshek - that's great!

**Comment by sebdalgarno** [comment]
Well I set up a better cell signal booster in my tree this morning and can now say I have successfuly downloaded the historic dataset! thanks @ateucher for the changes.

**Comment by ateucher** [comment]
Excellent! I have a bit more cleanup to do then I will merge this to master

**Comment by ateucher** [comment]
One thing I haven't tested is updating if you had an old version without using `burn_it_down()`. @J-krogh can you please try the above without using `burn_it_down()`? i.e.:

```r
remotes::install_github("bcgov/rems@sqlite-path")
library(rems)
download_historic_data()
read_historic_data(emsid = "0400203", from_date = as.Date("1984-11-20"),
                   to_date = as.Date("1991-05-11"))
```

**Comment by j-krogh** [comment]
@ateucher done, all seems to be working!

**Pull request merged**
