### PR TITLE
Convert mdl units

### PR DESCRIPTION
**Pull request by ateucher**

### CODE REVIEW

**Comment by ateucher** [comment]
Initial work to address https://github.com/bcgov/wqbc/issues/158. Unfortunately it's not very fast (~11 seconds for 5000 rows) due to having to loop over the rows, since `{units}` isn't vectorized over different units.

**Comment by ateucher** [comment]
@joethorley I think this is a pretty good solution, one TODO remaining.

**Comment by ateucher** [comment]
@joethorley @JessicaPenno @KarHarker @j-krogh I am ready to merge this - please have a look if you'd like. See the [README](https://github.com/bcgov/rems/tree/convert-mdl-units#units) for a brief demo of its usage.

**Comment by joethorley** [comment]
That is very elegant - hats off!

**Comment by ateucher** [comment]
Thanks Joe!

**Comment by JessicaPenno** [comment]
Awesome Andy!! I assume that I do not need to review the units table anymore, I have not got to that yet 

@joethorley how do we get this into ShinyREMs?

**Comment by ateucher** [comment]
Thanks @JessicaPenno - no you don't need to review it now :)

**Comment by joethorley** [comment]
@JessicaPenno - I think it needs to be added to the wqbc functions and then shinyrems will just need tweaking internally to make sure the data goes through this step.

**Pull request merged**
