### PR TITLE
New sqlite

### PR DESCRIPTION
**Pull request by ateucher**
Fixes for sqlite and updates to data on bcdc.

### CODE REVIEW

**Comment by ateucher** [comment]
This is in place of #52, allowing daily update of historic data.

@joethorley @sebdalgarno @KarHarker @j-krogh @JessicaPenno sorry to ask you again, but if you can test this that would be great! 

Please check out the [NEWS](https://github.com/bcgov/rems/blob/new-sqlite/NEWS.md) - as with the duckdb branch, I have added the `connect_historic_db()` function, that needs to be called before `attach_historic_data()`

**Comment by ateucher** [comment]
Forgot to mention. Please install with `remotes::install_github("bcgov/rems", ref = "new-sqlite")`

**Comment by joethorley** [comment]
Works for me

**Comment by ateucher** [comment]
Excellent, thanks Joe

**Comment by KarHarker** [comment]
works for me, too!

**Pull request merged**
